const PDFDocument = require('pdfkit');

/**
 * Generate a professional PDF report for a concrete mix design.
 *
 * @param {Object} design - Full design record from database
 * @returns {Buffer} PDF buffer
 */
const generateMixDesignPDF = (design) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];

    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const { mix_design, compliance, justification, qa_notes, field_tips, created_at } = design;
    const CLAY = '#C46A3C';
    const SLATE = '#3A3A3A';
    const DUSTY = '#7A8A8F';

    // ─── Header ────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill(CLAY);
    doc.fillColor('#fff').fontSize(22).font('Helvetica-Bold')
       .text('MIKSIR', 50, 25, { align: 'left' });
    doc.fontSize(11).font('Helvetica')
       .text('AI Concrete Mix Design Report', 50, 52, { align: 'left' });
    doc.text(new Date(created_at).toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' }),
       0, 52, { align: 'right', width: doc.page.width - 50 });

    doc.moveDown(3);

    // ─── Mix Proportions ───────────────────────────────────────
    section(doc, 'MIX PROPORTIONS (per m³ of concrete)', CLAY);

    const props = [
      ['Cement', `${mix_design.cement} kg/m³`],
      ['Water', `${mix_design.water} kg/m³`],
      ['Fine Aggregate (SSD)', `${mix_design.fine_aggregate_ssd} kg/m³`],
      ['Coarse Aggregate (SSD)', `${mix_design.coarse_aggregate_ssd} kg/m³`],
      ['Air Content', `${mix_design.air_content_pct}%`],
      ['w/c Ratio', mix_design.w_c_ratio],
      ['Target Mean Strength', `${mix_design.target_mean_strength} MPa`],
      ['Unit Weight (fresh)', `${mix_design.unit_weight} kg/m³`],
    ];

    if (mix_design.admixtures && Object.keys(mix_design.admixtures).length) {
      Object.entries(mix_design.admixtures).forEach(([k, v]) => {
        props.push([`Admixture: ${k}`, `${v} kg/m³`]);
      });
    }

    table(doc, props, SLATE, DUSTY);

    // ─── Batching Quantities ──────────────────────────────────
    section(doc, 'BATCHING QUANTITIES (current aggregate moisture)', CLAY);
    table(doc, [
      ['Cement', `${mix_design.batching.cement} kg`],
      ['Water to Add', `${mix_design.batching.water_to_add} kg`],
      ['Fine Aggregate (current)', `${mix_design.batching.fine_aggregate} kg`],
      ['Coarse Aggregate (current)', `${mix_design.batching.coarse_aggregate} kg`],
    ], SLATE, DUSTY);

    // ─── Volumetric Breakdown ─────────────────────────────────
    section(doc, 'VOLUMETRIC BREAKDOWN (m³ per m³ concrete)', CLAY);
    table(doc, Object.entries(mix_design.volumes).map(([k, v]) => [
      k.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase()), `${v} m³`
    ]), SLATE, DUSTY);

    // ─── Compliance Checks ────────────────────────────────────
    section(doc, `COMPLIANCE — ${compliance.code}  [${compliance.overall}]`, CLAY);

    compliance.checks.forEach((c) => {
      const color = c.status === 'PASS' ? '#27ae60' : c.status === 'WARNING' ? '#e67e22' : '#c0392b';
      doc.fontSize(10).fillColor(color).font('Helvetica-Bold').text(`  ● ${c.status}`, { continued: true });
      doc.fillColor(SLATE).font('Helvetica').text(`  ${c.description}`);
      if (c.required !== undefined) doc.fillColor(DUSTY).fontSize(9).text(`       Required: ${c.required}  |  Actual: ${c.actual}${c.unit ? ' ' + c.unit : ''}`);
      if (c.limit !== undefined) doc.fillColor(DUSTY).fontSize(9).text(`       Limit: ${c.limit}  |  Actual: ${c.actual}`);
      doc.moveDown(0.3);
    });

    // ─── Justification ────────────────────────────────────────
    section(doc, 'DESIGN JUSTIFICATION', CLAY);
    Object.entries(justification).forEach(([k, v]) => {
      doc.fontSize(10).fillColor(CLAY).font('Helvetica-Bold')
         .text(k.replace(/_/g, ' ').toUpperCase() + ':', { continued: true });
      doc.fillColor(SLATE).font('Helvetica').text('  ' + v);
      doc.moveDown(0.3);
    });

    // ─── QA Notes ────────────────────────────────────────────
    if (qa_notes) {
      section(doc, 'QA NOTES', CLAY);
      doc.fontSize(10).fillColor(SLATE).font('Helvetica').text(qa_notes);
      doc.moveDown();
    }

    // ─── Field Tips ───────────────────────────────────────────
    if (field_tips?.length) {
      section(doc, 'FIELD TIPS', CLAY);
      field_tips.forEach((tip, i) => {
        doc.fontSize(10).fillColor(SLATE).font('Helvetica').text(`${i + 1}. ${tip}`);
        doc.moveDown(0.3);
      });
    }

    // ─── Footer ───────────────────────────────────────────────
    doc.fontSize(8).fillColor(DUSTY).font('Helvetica')
       .text('Generated by Miksir AI — For engineering validation only. Verify all values with a qualified structural engineer before use.',
             50, doc.page.height - 40, { align: 'center', width: doc.page.width - 100 });

    doc.end();
  });
};

// ─── Helpers ─────────────────────────────────────────────────────

const section = (doc, title, color) => {
  doc.moveDown(0.5);
  doc.fontSize(11).fillColor(color).font('Helvetica-Bold').text(title);
  doc.moveTo(50, doc.y + 2).lineTo(doc.page.width - 50, doc.y + 2).strokeColor(color).lineWidth(1).stroke();
  doc.moveDown(0.5);
};

const table = (doc, rows, textColor, altColor) => {
  rows.forEach(([label, value], i) => {
    const bg = i % 2 === 0 ? '#FAFAF8' : '#F5F3EF';
    const y = doc.y;
    doc.rect(50, y, doc.page.width - 100, 18).fill(bg);
    doc.fillColor(altColor).fontSize(9).font('Helvetica').text(label, 60, y + 4, { continued: true, width: 220 });
    doc.fillColor(textColor).font('Helvetica-Bold').text(String(value), 280, y + 4);
    doc.y = y + 20;
  });
  doc.moveDown(0.5);
};

module.exports = { generateMixDesignPDF };
